 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/professors", type: :request do
  # Professor. As you add validations to Professor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Professor.create! valid_attributes
      get professors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      professor = Professor.create! valid_attributes
      get professor_url(professor)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_professor_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      professor = Professor.create! valid_attributes
      get edit_professor_url(professor)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Professor" do
        expect {
          post professors_url, params: { professor: valid_attributes }
        }.to change(Professor, :count).by(1)
      end

      it "redirects to the created professor" do
        post professors_url, params: { professor: valid_attributes }
        expect(response).to redirect_to(professor_url(Professor.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Professor" do
        expect {
          post professors_url, params: { professor: invalid_attributes }
        }.to change(Professor, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post professors_url, params: { professor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested professor" do
        professor = Professor.create! valid_attributes
        patch professor_url(professor), params: { professor: new_attributes }
        professor.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the professor" do
        professor = Professor.create! valid_attributes
        patch professor_url(professor), params: { professor: new_attributes }
        professor.reload
        expect(response).to redirect_to(professor_url(professor))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        professor = Professor.create! valid_attributes
        patch professor_url(professor), params: { professor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested professor" do
      professor = Professor.create! valid_attributes
      expect {
        delete professor_url(professor)
      }.to change(Professor, :count).by(-1)
    end

    it "redirects to the professors list" do
      professor = Professor.create! valid_attributes
      delete professor_url(professor)
      expect(response).to redirect_to(professors_url)
    end
  end
end
